services:
  - type: web
    name: sponsorindex-scheduler
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
    healthCheckPath: /health 

databases:
  - name: scheduler-db
    plan: free
    ipAllowList: [] # allow all 